//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Comments = new HashSet<Comment>();
            this.Favourites = new HashSet<Favourite>();
            this.Favourites1 = new HashSet<Favourite>();
            this.MCQs = new HashSet<MCQ>();
            this.Mistakes = new HashSet<Mistake>();
            this.Ratings = new HashSet<Rating>();
            this.SuggestedVideos = new HashSet<SuggestedVideo>();
            this.SuggestedVideos1 = new HashSet<SuggestedVideo>();
            this.WishLists = new HashSet<WishList>();
            this.WishLists1 = new HashSet<WishList>();
            this.NewRelDbs = new HashSet<NewRelDb>();
        }
    
        public int ArticleNo { get; set; }
        public string ArticleName { get; set; }
        public short TopicId { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Favourite> Favourites { get; set; }
        public virtual ICollection<Favourite> Favourites1 { get; set; }
        public virtual ICollection<MCQ> MCQs { get; set; }
        public virtual ICollection<Mistake> Mistakes { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<SuggestedVideo> SuggestedVideos { get; set; }
        public virtual ICollection<SuggestedVideo> SuggestedVideos1 { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
        public virtual ICollection<WishList> WishLists1 { get; set; }

        public virtual ICollection<NewRelDb> NewRelDbs { get; set; }
    }
}
