//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public int ChoiceNo { get; set; }
        public string AnswerChoiceId { get; set; }
        public byte QuestionNo { get; set; }
        public string Choice_A_B_C_D_ { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
