//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCQTAKEN
    {
        public short TakenNo { get; set; }
        public int Marks { get; set; }
        public System.DateTime Takendate { get; set; }
        public string TimeTook { get; set; }
        public int QuestionSetNo { get; set; }
        public long UserId { get; set; }
    
        public virtual MCQ MCQ { get; set; }
        public virtual User User { get; set; }
    }
}
