//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewRelDb
    {
        public int ID { get; set; }
        public string Field1 { get; set; }
        public int ArticleNo { get; set; }
        public int MistakeNo { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Mistake Mistake { get; set; }
    }
}
