//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public byte NotiNo { get; set; }
        public long userId { get; set; }
        public string Display { get; set; }
        public string MailID { get; set; }
    
        public virtual User User { get; set; }
    }
}
