//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Choices = new HashSet<Choice>();
        }
    
        public byte QuestionNo { get; set; }
        public int QuestionSetNo { get; set; }
        public string Description { get; set; }
        public int PinpointTime { get; set; }
        public string AnswerChoiceId { get; set; }
        public Nullable<byte> Learned { get; set; }
        public Nullable<byte> Notlearned { get; set; }
    
        public virtual ICollection<Choice> Choices { get; set; }
        public virtual MCQ MCQ { get; set; }
    }
}
