//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Favourites = new HashSet<Favourite>();
            this.MakeMcqQuestions = new HashSet<MakeMcqQuestion>();
            this.MCQTAKENs = new HashSet<MCQTAKEN>();
            this.Mistakes = new HashSet<Mistake>();
            this.Notifications = new HashSet<Notification>();
            this.NotificationSeens = new HashSet<NotificationSeen>();
            this.Profiles = new HashSet<Profile>();
            this.Ratings = new HashSet<Rating>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public long UserID { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Favourite> Favourites { get; set; }
        public virtual ICollection<MakeMcqQuestion> MakeMcqQuestions { get; set; }
        public virtual ICollection<MCQTAKEN> MCQTAKENs { get; set; }
        public virtual ICollection<Mistake> Mistakes { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<NotificationSeen> NotificationSeens { get; set; }
        public virtual ICollection<Profile> Profiles { get; set; }
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
