//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int ListNo { get; set; }
        public long UserID { get; set; }
        public int ArticleNo { get; set; }
        public short TopicNo { get; set; }
        public Nullable<System.DateTime> EnlistedDate { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Article Article1 { get; set; }
        public virtual User User { get; set; }
    }
}
